#!/bin/bash
#/sbin/ifconfig ${1##/*/} hw ether 80:00:00:00:00:01
#/sbin/ifconfig ${1##/*/} up promisc
/sbin/ifconfig ${1##/*/} up 
# /sbin/ifconfig ${1##/*/} down
/usr/sbin/brctl addif br0 ${1##/*/}

